export const CONFIG = {
  storageKey: 'kolobok_save',
  saveVersion: 4,

  stats: {
    start: 120,
    min: 0,
    max: 120,
  },

  statZones: {
    red: { max: 20 },
    yellow: { max: 50 },
    green: { max: 100 },
    gold: { max: 120 },
  },

  statDecay: {
    tickMs: 10000,
    homeSlowdown: 1.5,
    /** Отображаемый % полоски (0–100) за 90 мин при весе 1; при max 120 ≈ 1.2 пункта */
    displayPercentPer90Min: 1,
    hunger: 1,
    thirst: 1,
    health: 1,
    mood: 1,
    runMultiplier: 3,
  },

  timers: {
    phraseRotateMs: 20000,
    autosaveMs: 5000,
  },

  statColors: {
    hunger: { from: '#FF8C42', to: '#FFB84D' },
    thirst: { from: '#4A9EFF', to: '#6BB6FF' },
    health: { from: '#FF5E7E', to: '#FF8FA3' },
    mood: { from: '#FFD93D', to: '#FFE873' },
  },

  homeParticles: {
    count: 10,
    speedMin: 0.15,
    speedMax: 0.35,
    drift: 0.08,
    opacityMin: 0.3,
    opacityMax: 0.6,
  },

  clicker: {
    pointsMin: 1,
    pointsMax: 3,
    vibrateMs: 8,
    squashMs: 85,
    particlesMin: 1,
    particlesMax: 3,
    maxParticles: 56,
    particleLifeMs: 480,
    spreadMinVw: 3,
    spreadMaxVw: 14,
    riseMinVh: 6,
    riseMaxVh: 13,
    emojis: ['✨', '⭐', '🟡', '💫', '⚡'],
    phraseOnTapChance: 0.1,
  },

  homeFoods: {
    firstDelayMs: 800,
    intervalMinMs: 2800,
    intervalMaxMs: 4500,
    minOnScreen: 5,
    maxOnScreen: 14,
    dynamicMax: {
      base: 5,
      cap: 14,
      everyInteractions: 4,
      plusPerStep: 1,
    },
    waterSpawnBias: 0.4,
    badSpawnChance: 0.28,
    neutralSpawnChance: 0.32,
    bad: {
      points: -1,
    },
    good: {
      points: 1,
    },
    badTip: {
      enabled: true,
      text:
        'Слышь, это не ПП-перекус. Тапнешь или порежешь — звёздочка уйдёт на −1. Сам решай, бро.',
      buttonText: 'Понятно',
    },
    badFx: {
      bomb: {
        ms: 780,
        shakeMs: 420,
        ringCount: 3,
        debrisCount: 16,
        debrisDistMin: 2.2,
        debrisDistMax: 3.8,
      },
    },
    statBoostPerPoints: 1000,
    statBoostAmount: 1,
    lifetimeMs: 8000,
    expireFadeMs: 500,
    flyMs: 300,
    tapBurst: {
      ms: 460,
      ghostFlyMs: 280,
      ghostDelayMs: 140,
      particleCount: 9,
      particleDistMin: 1.5,
      particleDistMax: 2.6,
    },
    eatAnimMs: 300,
    spawnPopMs: 380,
    marginPercent: 6,
    spawnRadiusPercent: 8.5,
    minCenterGapPercent: 19,
    maxOverlapPercent: 2.5,
    positionAttempts: 32,
    forbiddenZone: { leftMin: 28, leftMax: 72, topMin: 38, topMax: 92 },
    slice: {
      minDrawPx: 8,
      minSegmentPx: 4,
      sliceStepPx: 12,
      trailWidth: 4.5,
      trailFadeAlpha: 0.02,
      trailColor: 'rgba(255, 245, 220, 0.94)',
      trailGlowBlur: 5,
      trailFadeMs: 380,
      tapMaxMovePx: 14,
      hitPaddingPx: 10,
      scoreMultiplier: 1.65,
      scoreBonus: 5,
      badScoreMultiplier: 1.2,
      fxMs: 480,
      vibrateMs: [14, 22, 16],
      badVibrateMs: [36, 24, 32, 18],
      bombVibrateMs: [36, 24, 32, 18],
    },
    list: [
      { id: 'water', emoji: '💧', name: 'Вода', kind: 'good', thirstPriority: true },
      { id: 'tea', emoji: '🍵', name: 'Чай', kind: 'good', thirstPriority: true },
      { id: 'juice', emoji: '🧃', name: 'Сок', kind: 'good', thirstPriority: true },
      { id: 'milk', emoji: '🥛', name: 'Молоко', kind: 'good', thirstPriority: true },
      { id: 'apple', emoji: '🍎', name: 'Яблоко', kind: 'good' },
      { id: 'banana', emoji: '🍌', name: 'Банан', kind: 'good' },
      { id: 'broccoli', emoji: '🥦', name: 'Брокколи', kind: 'good' },
      { id: 'orange', emoji: '🍊', name: 'Апельсин', kind: 'good' },
      { id: 'carrot', emoji: '🥕', name: 'Морковка', kind: 'good' },
      { id: 'salad', emoji: '🥗', name: 'Салат', kind: 'good' },
      { id: 'yogurt', emoji: '🥣', name: 'Йогурт', kind: 'good' },
      { id: 'cucumber', emoji: '🥒', name: 'Огурец', kind: 'good' },
      { id: 'tomato', emoji: '🍅', name: 'Помидор', kind: 'good' },
      { id: 'grape', emoji: '🍇', name: 'Виноград', kind: 'good' },
      { id: 'strawberry', emoji: '🍓', name: 'Клубника', kind: 'good' },
      { id: 'pear', emoji: '🍐', name: 'Груша', kind: 'good' },
      { id: 'kiwi', emoji: '🥝', name: 'Киви', kind: 'good' },
      { id: 'avocado', emoji: '🥑', name: 'Авокадо', kind: 'good' },
      { id: 'fish', emoji: '🐟', name: 'Рыба', kind: 'good' },
      { id: 'bread', emoji: '🍞', name: 'Хлеб', kind: 'neutral' },
      { id: 'eggs', emoji: '🥚', name: 'Яйца', kind: 'neutral' },
      { id: 'cheese', emoji: '🧀', name: 'Сыр', kind: 'neutral' },
      { id: 'coffee', emoji: '☕', name: 'Кофе', kind: 'neutral' },
      { id: 'chicken', emoji: '🍗', name: 'Курица', kind: 'neutral' },
      { id: 'rice', emoji: '🍚', name: 'Рис', kind: 'neutral' },
      { id: 'pasta', emoji: '🍝', name: 'Паста', kind: 'neutral' },
      { id: 'meat', emoji: '🥩', name: 'Мясо', kind: 'neutral' },
      { id: 'potato', emoji: '🥔', name: 'Картошка', kind: 'neutral' },
      { id: 'corn', emoji: '🌽', name: 'Кукуруза', kind: 'neutral' },
      { id: 'peanut', emoji: '🥜', name: 'Арахис', kind: 'neutral' },
      { id: 'beer', emoji: '🍺', name: 'Пиво', kind: 'bad' },
      { id: 'pizza', emoji: '🍕', name: 'Пицца', kind: 'bad' },
      { id: 'chocolate', emoji: '🍫', name: 'Шоколад', kind: 'bad' },
      { id: 'cola', emoji: '🥤', name: 'Кола', kind: 'bad' },
      { id: 'chips', emoji: '🥨', name: 'Чипсы', kind: 'bad' },
      { id: 'burger', emoji: '🍔', name: 'Бургер', kind: 'bad' },
      { id: 'hotdog', emoji: '🌭', name: 'Хот-дог', kind: 'bad' },
      { id: 'candy', emoji: '🍬', name: 'Конфеты', kind: 'bad' },
      { id: 'icecream', emoji: '🍦', name: 'Мороженое', kind: 'bad' },
      { id: 'donut', emoji: '🍩', name: 'Пончик', kind: 'bad' },
      { id: 'cake', emoji: '🍰', name: 'Торт', kind: 'bad' },
      { id: 'cookie', emoji: '🍪', name: 'Печенье', kind: 'bad' },
      { id: 'fries', emoji: '🥡', name: 'Фри', kind: 'bad' },
      { id: 'nachos', emoji: '🌮', name: 'Начос', kind: 'bad' },
      { id: 'sausage', emoji: '🌭', name: 'Сосиска', kind: 'bad' },
      { id: 'energy', emoji: '⚡', name: 'Энергетик', kind: 'bad' },
      { id: 'lollipop', emoji: '🍭', name: 'Леденец', kind: 'bad' },
    ],
  },

  unpacking: {
    step1Ms: 2000,
    confettiCount: 18,
    receiptAutoAdvanceMs: 5000,
    statBoostFallback: { hunger: 25, thirst: 20, health: 25, mood: 12 },
    orbitSlots: [
      { left: 72, top: 36 },
      { left: 82, top: 50 },
      { left: 65, top: 58 },
      { left: 16, top: 44 },
      { left: 22, top: 58 },
    ],
  },

  criticalStat: {
    threshold: 15,
    warnIntervalMs: 30000,
  },

  replies: {
    idleHideMs: 4000,
    idleLongChars: 50,
    reactionLifeMs: 1400,
    nutritionChance: 0.15,
    nutritionDismissOnTapMs: 1500,
  },

  tutorial: {
    spotlightPad: 10,
    foodHint: 'тап или свайп',
    dimStrong: 'rgba(0, 0, 0, 0.75)',
    dimLight: 'rgba(0, 0, 0, 0.45)',
    steps: [
      {
        id: 'welcome',
        targetSelector: '',
        cardPlacement: 'center',
        text: 'Привет! Я Колобок. Теперь живу с тобой. Покажу всё за минуту.',
        buttonText: 'Поехали 🚀',
      },
      {
        id: 'stats',
        targetSelector: '#stats-bars',
        cardPlacement: 'bottom',
        text: 'Это мои показатели. Сытость, Жажда, Здоровье, Настроение. Чем выше — тем я бодрее.',
        buttonText: 'Понял 👌',
      },
      {
        id: 'score',
        targetSelector: '#score-hub',
        cardPlacement: 'bottom',
        text: 'За тапы и забеги копятся очки. На них покупаешь шмот, домики, плюшки.',
        buttonText: 'Круто',
      },
      {
        id: 'floating_food',
        targetSelector: '.stage-hero',
        cardPlacement: 'bottom',
        dim: 'light',
        text: 'Летающую еду тапай или режь свайпом. Зелёное и жёлтое — +1 звезда, красное — −1 звезда, статы не трогает.',
        action: 'wait_for_tap',
      },
      {
        id: 'receipt',
        targetSelector: '#btn-receipt',
        cardPlacement: 'top',
        text: 'Сюда падают твои реальные покупки из Пятёрочки, Перекрёстка или Чижика. Разбираю чек — комментирую с иронией, без менторства.',
        buttonText: 'Пошли дальше',
      },
      {
        id: 'run',
        targetSelector: '#btn-run',
        cardPlacement: 'top',
        text: 'Переел? Гоним в мини-игры. Раннер, тапалки. Я сжигаю калории, ты копишь очки.',
        buttonText: 'Запомнил',
      },
      {
        id: 'speech_example',
        targetSelector: '',
        cardPlacement: 'bottom',
        dim: 'light',
        text: 'Главное: я даю советы на основе ТВОИХ покупок. Не нравится — игнорь.',
        buttonText: 'Спасибо!',
        demoSpeech: 'Кофе зашёл. Бодрость в деле, бро.',
      },
    ],
  },

  lecture: {
    tapChance: 0.12,
    purchaseReviewChance: 0.35,
    dismissLabels: [
      'Понял, бро',
      'Ок, запомнил',
      'Ладно, не буду',
      'Услышал, красавчик',
      'Принял, не обижайся',
      'Ясно, не грузи',
    ],
  },

  moodThresholds: {
    hungerLow: 20,
    thirstLow: 20,
    healthLow: 30,
    angryMood: 20,
    moodHigh: 80,
    allGoodMin: 50,
    allGoodMax: 70,
    overstuffed: 95,
    sleepyHunger: 110,
    burnRunAbove: 100,
  },

  loader: {
    minShowMs: 1800,
    hideFadeMs: 500,
    afterLoadPauseMs: 400,
    videoTimeoutMs: 8000,
    tipRotateMs: 2400,
    logoSrc: 'assets/kolobok/logo.png',
    doneTip: 'Погнали, бро — колобок на связи 🟡',
    tips: [
      'Качаем мышцы из теста…',
      'Не булка — значит, не вздуемся.',
      'Бабка в очереди. Ты — в зале.',
      'Скоро можно будет затапить.',
      'Спортивный режим: включён.',
    ],
  },

  kolobokHome: {
    videoType: 'video/webm',
    preloadBeforeEndSec: 1,
    prerollBeforeEndSec: 0.12,
    videos: [
      {
        src: 'assets/kolobok/kolobok-home.webm',
        poster: 'assets/kolobok/kolobok-home-poster.jpg',
      },
      {
        src: 'assets/kolobok/kolobok-home-2.webm',
        poster: 'assets/kolobok/kolobok-home-2-poster.jpg',
      },
      {
        src: 'assets/kolobok/kolobok-home-3.webm',
        poster: 'assets/kolobok/kolobok-home-3-poster.jpg',
      },
    ],
  },

  statBars: [
    { key: 'hunger', label: 'Сытость', icon: '🍗' },
    { key: 'thirst', label: 'Жажда', icon: '💧' },
    { key: 'health', label: 'Здоровье', icon: '❤️' },
    { key: 'mood', label: 'Настроение', icon: '😎' },
  ],

  topPanel: {
    statFillColors: {
      hunger: '#F5A623',
      thirst: '#4FB3F5',
      health: '#E25C5C',
      mood: '#B57BE0',
    },
    statThemes: {
      hunger: { rgb: '245, 166, 35', hex: '#F5A623', dark: '#C48412' },
      thirst: { rgb: '79, 179, 245', hex: '#4FB3F5', dark: '#2E8BC4' },
      health: { rgb: '226, 92, 92', hex: '#E25C5C', dark: '#B83A3A' },
      mood: { rgb: '181, 123, 224', hex: '#B57BE0', dark: '#8B4FB8' },
    },
    statChipLabels: {
      hunger: 'СЫТОСТЬ',
      thirst: 'ЖАЖДА',
      health: 'ЗДОРОВЬЕ',
      mood: 'НАСТРОЕНИЕ',
    },
    criticalRatio: 0.15,
    statTipHideMs: 1500,
    menuItems: [
      { icon: '🔊', label: 'Звук' },
      { icon: '📳', label: 'Вибрация' },
      { icon: '📜', label: 'Правила игры' },
      { icon: '💬', label: 'Поддержка' },
      { icon: '🗑', label: 'Сбросить прогресс', action: 'resetProgress' },
    ],
    resetConfirm: 'Сбросить весь прогресс? Очки обнулятся, статы вернутся к старту.',
    exit: {
      title: 'Выйти из игры?',
      text: 'Прогресс сохранён ✅\nКолобок будет ждать 🥺',
      stayLabel: 'Остаться',
      leaveLabel: 'Выйти',
    },
  },

  purchase: {
    testMode: true,
    itemCountMin: 3,
    itemCountMax: 5,
    receiptMinStat: 20,
    statBoostAll: 50,
    testPhases: {
      arrivalMs: 500,
      receiptRevealMs: 500,
      receiptLineDelayMs: 80,
      itemPopDelayMs: 120,
      itemFlyMs: 350,
      packageLeaveMs: 400,
      floatShowMs: 600,
      bulkBoostPauseMs: 400,
    },
    layout: {
      arcStartAngle: 0.15,
      arcEndAngle: 0.85,
      arcRadiusX: 34,
      arcRadiusY: 12,
      arcCenterY: 88,
      flyTargetY: 38,
    },
    phases: {
      arrivalMs: 1500,
      receiptRevealMs: 1500,
      receiptLineDelayMs: 200,
      itemPopDelayMs: 300,
      itemFlyMs: 550,
      packageLeaveMs: 900,
      floatShowMs: 1200,
      bulkBoostPauseMs: 900,
    },
  },

  items: [
    { id: 'milk', emoji: '🥛', name: 'Молоко', price: 89, effects: { hunger: 10 } },
    { id: 'bread', emoji: '🍞', name: 'Хлеб', price: 45, effects: { hunger: 12 } },
    { id: 'cheese', emoji: '🧀', name: 'Сыр', price: 199, effects: { hunger: 15 } },
    { id: 'chocolate', emoji: '🍫', name: 'Шоколадка', price: 79, effects: { hunger: 8, mood: 10 } },
    { id: 'cola', emoji: '🥤', name: 'Кола', price: 120, effects: { thirst: 12 } },
    { id: 'beer', emoji: '🍺', name: 'Пиво', price: 89, effects: { mood: 15, health: -5 } },
    { id: 'broccoli', emoji: '🥦', name: 'Брокколи', price: 99, effects: { health: 10 } },
    { id: 'apple', emoji: '🍎', name: 'Яблоко', price: 35, effects: { health: 8 } },
    { id: 'pizza', emoji: '🍕', name: 'Пицца', price: 350, effects: { hunger: 20, mood: 10 } },
    { id: 'meat', emoji: '🥩', name: 'Мясо', price: 450, effects: { hunger: 25 } },
    { id: 'chicken', emoji: '🍗', name: 'Курица', price: 290, effects: { hunger: 20 } },
    { id: 'coffee', emoji: '☕', name: 'Кофе', price: 150, effects: { mood: 10 } },
    { id: 'icecream', emoji: '🍦', name: 'Мороженое', price: 99, effects: { mood: 15 } },
    { id: 'banana', emoji: '🍌', name: 'Банан', price: 25, effects: { hunger: 5, health: 5 } },
    { id: 'eggs', emoji: '🥚', name: 'Яйца', price: 89, effects: { hunger: 10 } },
  ],

  ui: {
    receiptStoreHeading: 'Чек · Пятёрочка / Перекрёсток / Чижик',
    unpackButton: 'Распаковать покупки',
    openBagButton: 'Открыть пакет 📦',
    runButton: 'Сжечь калории',
    runButtonIcon: '🔥',
    receiptButtonIcon: '🛒',
    speechHideIdleMs: 6000,
    hapticTapMs: 10,
    hapticAchievement: [50, 30, 50],
    tapMoodBonus: 1,
    statLowPercent: 30,
    receiptBlockedPhrases: [
      'Распаковка только когда хоть один стат в красной зоне, бро.',
      'Всё норм — в магазин не ходили. Отдохни.',
      'Показатели не в жопе — покупки подождут.',
    ],
    stubRunPhrases: [
      'Бежать хочешь? Раннер на подходе. Пока отдыхай.',
      'Ноги чешутся — норм. Этап 3, брат, скоро.',
      'От бабки убежишь потом. Сейчас — домашний режим.',
    ],
  },
};
